#!bin/zsh

function git_commit() {
  dt=$(date '+%Y-%m-%dT%H:%M:%S')
  menv=$(echo $env | tr '[:lower:]' '[:upper:]')

  if [ -n "$1" ]
    then
      mes="$menv $dt $1"
    else
      mes="$menv $dt end of session"
  fi

  git add .
  git commit -S -m $mes
}