#!bin/zsh

function git_create_sshkey() {
	echo "Setting up SSH Key"
  if [[ ! -d ~/.ssh ]]; then
    mkdir -p ~/.ssh
    echo "Directory ~/.ssh created."
  fi

  if [[ "$1" == "lab" ]]; then
    git_email="MYGITEMAIL"
    gitID="gitlabID"
    gitwww="https://gitlab.com/-/user_settings/ssh_keys"
  elif [[ "$1" == "hub" ]]; then
    git_email="MYGITEMAIL"
    gitID="githubID"
    gitwww="https://github.com/settings/ssh/new"
  else
    echo "You need to give lab or hub as an argument"
    return 1 
  fi
  
  ssh-keygen -t ed25519 -C $git_email -f "$HOME/.ssh/$gitID" -N ""
  echo "New SSH key generated"
  cat ~/.ssh/$gitID.pub | clip.exe
  cmd.exe /C start $gitwww
  echo "Your new SSH key was added to your clipboard, add it to Git$1"
  echo "Press any key when your key was added to Git$1"
  read -nsk 1

  git_add_hosts $1
  echo "Your Git$1 SSH key is now set up!"
}

