#!bin/zsh

# Update Oh-My-Posh
function omp_install {
  curl -s https://ohmyposh.dev/install.sh | sh -s
  
  omp_new=$(oh-my-posh --version)
  echo "You have installed oh-my-posh version: "${HL} $omp_new ${NS}
}