#!/bin/zsh

#----------------------------------------------------------------
# MAN PAGE COLORS
#----------------------------------------------------------------

# If these are too early, then it doesn't work
export LESS_TERMCAP_mb=$'\E[01;94m'
export LESS_TERMCAP_md=$'\E[01;94m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;37m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;33m'


#----------------------------------------------------------------
# SURROUNDING
# Source: https://thevaluable.dev/zsh-install-configure-mouseless/
#----------------------------------------------------------------

autoload -Uz surround
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -M vicmd cs change-surround
bindkey -M vicmd ds delete-surround
bindkey -M vicmd ys add-surround
bindkey -M visual S add-surround